### PR TITLE
#31 Updated the DSM report plugin to support Java 8

### PR DESCRIPTION
**Pull request by jimbethancourt**
Updated the DSM plugin to support Java 8 by updating the dtangler dependency and updating the package imports.  I have also updated the Java version in the compiler plugin to use Java 8 and take advantage of some of the newer Java features (only minor code changes).

I added the maven-plugin-plugin since the mojo descriptors weren't being generated correctly.

I have successfully tested locally against a Java 8 project.

Will need to be compiled with a Java 8 compiler.

### CODE REVIEW

**Comment by romani** [comment]
https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

looks like oraclejdk7 is not on travis anymore.
please remove it from .travis.yml to let CI pass.

**Comment by romani** [comment]
I tested it on checkstyle project, it works, report is generated.
But looks like there is problem in DSM matric content generation, some cycles I do not see in code, but this is completely different issue.


@jimbethancourt , please update travis.yml , squash all commits in one , and I am ready to merge.

**Comment by jimbethancourt** [comment]
Hi @romani,
I have added oraclejdk8 to the Travis build config and removed all other JDKs, and it passed for JDK8, though it looks like it may be using the travis.yml from this repo and won't update until this PR is merged in.

Unfortunately, it looks like I don't have the ability to squash and merge from the pull request since I do not have write permissions in this repository if I am reading https://help.github.com/articles/about-pull-request-merges/ correctly.  However, it looks like there are no conflicts and squashing may not be required.

I haven't changed the dtangler algorithm (though I agree it looks like it could use some work).

**Comment by romani** [comment]
Squash all in your branch , do push to remote with force, GitHub will refresh PR automatically

**Comment by jimbethancourt** [comment]
Commits squashed and force pushed.

**Pull request merged**
